version: '3'

services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: GrupoESC_*
      ACCEPT_EULA: "Y"
    ports:      
       - "1433:1433"
    networks:
       - mynetwork


  web:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:      
       - "8050:80"
    depends_on:
       - db
    networks:
       - mynetwork

  portainer:
    image: portainer/portainer
    container_name: portainerTrabFinal
    ports:
      - "9000:9000"
    restart: always
    networks:
      - mynetwork
    volumes:
      - portainer_data:/data

volumes:
  portainer_data:
    external: true

networks:
  mynetwork:
    driver: bridge  